### ISSUE TITLE
Please consider switching to MIT license

### ISSUE THREAD

**Issue by robertlevy** [uberstudio/angular-flowtype#3]
would like to leverage this instead of recreating it but we can't use GPL.  note that flowtype itself is MIT

**Comment by uberstudio** [comment]
I removed the license altogether, no reason for this tiny piece of code to be restricted.

**Comment by robertlevy** [comment]
thanks for the quick response!  would you mind removing the license line in the bower file as well?

**Comment by uberstudio** [comment]
Done deal.
